### ISSUE TITLE
Object #<OutEndpoint> has no method 'startStream'

### ISSUE THREAD

**Issue by armaseg** [StadiumRunner/node-escpos#5]
I'm trying to execute "npm test" and I'm getting the folowing error.

```
> grunt nodeunit

Running "nodeunit:all" (nodeunit) task
Testing printer-test.js.F.
>> testPrint
>> TypeError: Object #<OutEndpoint> has no method 'startStream'
>> at Printer.print (lib/printer.js:151:10)
>> at Object.exports.testPrint (test/printer-test.js:20:10)

Fatal error: Object #<OutEndpoint> has no method 'startStream'
```

Please, may you help to solve this issue?

Thanks

**Comment by armaseg** [comment]
I found the problem, it looks like node-usb renamed the startStream function [ https://github.com/nonolith/node-usb/commit/ae0e3aad23bb09d5024585d216a24371b311f17b ]
I've been working with your project on Linux/Win and I'd like to submit a pull request. Is it ok for you?

**Comment by aminbh111** [comment]
startStream,stopStream and write  functions have been changed in node-usb .the project must use an older node-usb version or change function calls to the new once.
